#!/usr/bin/env bash
# build.sh — emit themes/city-blue.conf from the citypop palette + widget set
# forked from janoamaral/tokyo-night-tmux (citypop-tn fork).
# Re-run after editing palette or layout: bash build.sh && tmux source ~/.tmux.conf

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${OUT:-$REPO_DIR/themes/city-blue.conf}"
mkdir -p "$(dirname "$OUT")"

# ── Citypop palette (mirrors scripts/citypop/lib/palette.sh) ──
BG="#0a1929"
FG="#cdd9e5"
BBLACK="#1e4d7a"
BLUE="#4cc9f0"
CYAN="#56cfe1"
GREEN="#64dfdf"
BGREEN="#80ed99"

# ── Glyphs (Nerd Font, literal UTF-8 — keep file utf-8 encoded) ──
G_TERM="󰆍"        # terminal
G_SSH="󰣀"         # ssh
G_PREFIX="󰠠"      # prefix on
G_PREFIX_DIM="󰤂"  # prefix off
G_MENU="󰍜"        # menu
G_FOCUS="󱎫"       # focus stopwatch (count-up since session start)
G_SNAPSHOT="󰖲"    # snapshots (save/load named pane layouts) — window-restore
G_CPU="󰍛"         # cpu
G_RAM="󰘚"         # ram
G_DISK="󰋊"        # disk

# ── Widget script paths (resolved at tmux runtime) ──
# Keep $HOME literal in the emitted conf — tmux runs #(...) via /bin/sh,
# which expands $HOME per user. Baking an absolute path here would lock
# the generated conf to the build machine's user (breaks package managers
# and anyone whose $HOME differs from the builder's).
WIDGETS='$HOME/.tmux/scripts/citypop'
PLUG='$HOME/.tmux/plugins'

# ── Command stubs — these stay literal in the conf; tmux runs them every interval ──
# Read style options at build time (re-run build.sh after changing theme.conf)
WIN_STYLE="$(tmux show-option -gv @city-blue_window_id_style 2>/dev/null || echo none)"
ZOOM_STYLE="$(tmux show-option -gv @city-blue_zoom_id_style 2>/dev/null || echo dsquare)"
WIN_STYLE="${WIN_STYLE:-none}"
ZOOM_STYLE="${ZOOM_STYLE:-dsquare}"

netspeed_cmd="#($WIDGETS/netspeed.sh)"
git_cmd="#($WIDGETS/git-status.sh \\\"#{pane_current_path}\\\")"
window_number="#($WIDGETS/custom-number.sh #I $WIN_STYLE)"
zoom_number="#($WIDGETS/custom-number.sh #P $ZOOM_STYLE)"
datetime_cmd="#($WIDGETS/datetime-widget.sh)"
path_cmd="#($WIDGETS/path-widget.sh \\\"#{pane_current_path}\\\")"
battery_cmd="#($WIDGETS/battery-widget.sh)"
hostname_cmd="#($WIDGETS/hostname-widget.sh)"

focus_text="#($WIDGETS/focus-up.sh)"
cpu_text="#($PLUG/tmux-cpu/scripts/cpu_percentage.sh)"
ram_text="#($PLUG/tmux-cpu/scripts/ram_percentage.sh)"
disk_text="#($WIDGETS/disk-widget.sh)"
weather_text="#($WIDGETS/weather-text.sh)"
weather_icon="#($WIDGETS/weather-icon.sh)"
weather_refresh="#($PLUG/tmux-weather/scripts/weather.sh >/dev/null 2>&1)"

# ── Pills ──
pill() {
  printf "#[fg=%s,bg=%s,bold] %s #[fg=%s,bg=%s,nobold]%s %s" \
    "$BLUE" "$BBLACK" "$1" \
    "$FG" "$BBLACK" "$2" "$3"
}

FOCUS_PILL_INNER=$(pill "$G_FOCUS" "$focus_text" "")
FOCUS_PILL="#[range=user|focus_reset]${FOCUS_PILL_INNER}#[norange]"
SNAPSHOT_BUTTON="#[range=user|snapshots,fg=$BLUE,bg=$BBLACK,bold] $G_SNAPSHOT #[norange,default]"
CPU_PILL=$(pill "$G_CPU" "$cpu_text" "")
RAM_PILL=$(pill "$G_RAM" "$ram_text" "")
DISK_PILL=$(pill "$G_DISK" "$disk_text" "")
WEATHER_PILL=$(pill "$weather_icon" "$weather_text" "$weather_refresh")

# Window/session zone
RESET="#[fg=$FG,bg=$BG,nobold,noitalics,nounderscore,nodim]"
SESSION_PILL="#[fg=$BBLACK,bg=$BLUE,bold] #{?client_prefix,$G_PREFIX ,#[dim]$G_PREFIX_DIM }#[bold,nodim]#(whoami)${hostname_cmd}:#S #[default]"
MENU_BUTTON="#[range=user|sess_menu,fg=$BLUE,bg=$BBLACK,bold] $G_MENU #[norange,default]"

WIN_CURRENT="$RESET#[fg=$GREEN,bg=$BBLACK] #{?#{==:#{pane_current_command},ssh},$G_SSH ,$G_TERM }#[fg=$FG,bold,nodim]${window_number}#W#[nobold]#{?window_zoomed_flag, $zoom_number,} "
WIN_DEFAULT="$RESET#[fg=$FG] #{?#{==:#{pane_current_command},ssh},$G_SSH ,$G_TERM }${RESET}${window_number}#W#[nobold,dim]#{?window_zoomed_flag, $zoom_number,} "

RIGHT_TOP="${CPU_PILL}${RAM_PILL}${DISK_PILL}${WEATHER_PILL}${battery_cmd}${netspeed_cmd}"
RIGHT_BOTTOM="${FOCUS_PILL}${datetime_cmd}"

# ── Emit conf ──
cat > "$OUT" <<EOF
# ── city-blue — generated by build.sh ──
# Forked from janoamaral/tokyo-night-tmux via citypop-tn. See ATTRIBUTION.md.
# Re-run build.sh if Nerd Font glyphs ever disappear.

# ── Base ──
set -g status on
set -g status-position top
set -g status 2
set -g status-interval 5
set -g status-justify left
set -g status-left-length  80
set -g status-right-length 150

set -g status-style              "fg=$FG,bg=$BG"
set -g status-left-style         "fg=$FG,bg=$BG"
set -g status-right-style        "fg=$FG,bg=$BG"
set -g window-status-style          "fg=$FG,bg=$BG"
set -g window-status-current-style  "fg=$FG,bg=$BG"
set -g window-status-activity-style "fg=$FG,bg=$BG,none"
set -g window-status-bell-style     "fg=$FG,bg=$BG,none"
set -g window-status-last-style     "fg=$FG,bg=$BG"
set -g mode-style                "fg=$BGREEN,bg=$BBLACK"
set -g message-style             "bg=$BLUE,fg=$BBLACK"
set -g message-command-style     "fg=$BLUE,bg=$BBLACK"
set -g popup-border-style        "fg=$BLUE"

# ── Pane borders ──
set -g pane-border-lines heavy
set -g pane-border-style "fg=$BBLACK,bg=default"
set -g pane-active-border-style "fg=$CYAN,bg=default,bold"
set -g pane-border-status top
set -g pane-border-format "#[fg=$BBLACK,bg=default]─#[fg=$FG,bg=default] #{?pane_active,#[fg=$CYAN]●,#[fg=$BBLACK]○} #P #[fg=$BLUE]#{pane_current_command} #[fg=$FG,dim]#{=/24/...:pane_title}#[nodim] #[fg=$BBLACK,bg=default,dim]󰍽 right-click for menu #[nodim,fg=$BBLACK,bg=default]─"

# ── Window list ──
set -g window-status-separator ""
set -g window-status-current-format "${WIN_CURRENT}"
set -g window-status-format "${WIN_DEFAULT}"

# ── Status left/right (row 0) ──
set -g status-left "${MENU_BUTTON}${SESSION_PILL}"
set -g status-right "${git_cmd}${RIGHT_TOP}"

# ── Status row 1 (info) ──
set -g status-format[1] "#[bg=$BG,fg=$FG]${SNAPSHOT_BUTTON}#[bg=$BG,fg=$FG]${path_cmd}#[align=right,bg=$BG]${RIGHT_BOTTOM}"
EOF

echo "wrote $OUT"
