#!/usr/bin/env bash
# city-blue — clean rounded-badge tmux theme (tokyo-night-inspired layout).
# Builds ~/.tmux/themes/city-blue.conf with Nerd Font glyphs embedded
# as raw UTF-8 hex bytes so editors/clipboards can't strip them.
# Run: bash ~/.tmux/themes/build-city-blue.sh && tmux source ~/.tmux.conf

set -euo pipefail

# ── Nerd Font glyphs (UTF-8 hex) ──
G_FOLDER=$(printf '\xef\x81\xbb')          # U+F07B   folder
G_BRANCH=$(printf '\xee\x82\xa0')          # U+E0A0   powerline branch
G_CLOCK=$(printf '\xef\x80\x97')           # U+F017   clock
G_SUN=$(printf '\xef\x86\x85')             # U+F185   sun
G_TAG=$(printf '\xef\x80\xab')             # U+F02B   tag
G_BOLT=$(printf '\xe2\x9a\xa1')            # U+26A1   ⚡
G_CHECK=$(printf '\xe2\x9c\x93')           # U+2713   ✓
G_TOMATO=$(printf '\xf0\x9f\x8d\x85')      # U+1F345  🍅
G_PAUSE=$(printf '\xe2\x8f\xb8')           # U+23F8   ⏸
G_CPU=$(printf '\xef\x92\xbc')             # U+F4BC   cpu chip
G_USER=$(printf '\xef\x80\x87')            # U+F007   user
G_WIFI=$(printf '\xef\x87\xab')            # U+F1EB   wifi
G_NO_WIFI=$(printf '\xef\x9d\xb1')         # U+F771   wifi-off-ish

G_BATT_8=$(printf '\xef\x89\x80')          # U+F240   battery full
G_BATT_6=$(printf '\xef\x89\x81')          # U+F241
G_BATT_4=$(printf '\xef\x89\x82')          # U+F242
G_BATT_2=$(printf '\xef\x89\x83')          # U+F243
G_BATT_0=$(printf '\xef\x89\x84')          # U+F244

# Rounded powerline caps — left/right half-circle
PL_RL=$(printf '\xee\x82\xb6')             # U+E0B6
PL_RR=$(printf '\xee\x82\xb4')             # U+E0B4

OUT="$HOME/.tmux/themes/city-blue.conf"
mkdir -p "$(dirname "$OUT")"

# ── Palette (used many places — keep DRY via shell vars) ──
BG0="#1a0b2e"     # status row bg
BG1="#2d1b4e"     # window list inactive bg
BG2="#4a2c6d"     # raised panel
FG0="#f4e8d8"     # primary text
FG1="#c9b8e0"     # dim text
MAG="#ff2e88"     # neon pink (active window, message)
CYA="#4ddbff"     # ocean cyan (COPY, user)
MNT="#6bffb0"     # palm mint (NORMAL, online)
YEL="#ffd23f"     # glico yellow (PREFIX, battery)
ORG="#ff7f3f"     # sunset orange (weather, git)
PUR="#b366ff"     # vaporwave purple (session, host)
RED="#ff4d6d"     # takoyaki red (cpu high, bell)

# Badge helper — emits: cap_L color content cap_R
# Bash function for readability inside the heredoc.
badge() {
  local color="$1" text="$2"
  printf '#[fg=%s,bg=%s]%s#[bg=%s,fg=%s,bold] %s #[fg=%s,bg=%s]%s' \
    "$color" "$BG0" "$PL_RL" "$color" "$BG0" "$text" "$color" "$BG0" "$PL_RR"
}

# Badge with custom row bg (for row 1 sitting on bg0)
badge_on() {
  local color="$1" text="$2" rowbg="$3"
  printf '#[fg=%s,bg=%s]%s#[bg=%s,fg=%s,bold] %s #[fg=%s,bg=%s]%s' \
    "$color" "$rowbg" "$PL_RL" "$color" "$BG0" "$text" "$color" "$rowbg" "$PL_RR"
}

# Pre-compose badges
BADGE_NORMAL=$(badge "$MNT" "NORMAL")
BADGE_COPY=$(badge "$CYA" "COPY")
BADGE_PREFIX=$(badge "$YEL" "PREFIX")

# Conditional-safe variants: tmux #{?A,B,C} parses commas inside B/C unless
# escaped as #,. Replace every "," with "#," for badges used in conditionals.
BADGE_NORMAL_C="${BADGE_NORMAL//,/#,}"
BADGE_COPY_C="${BADGE_COPY//,/#,}"
BADGE_PREFIX_C="${BADGE_PREFIX//,/#,}"
BADGE_SESSION=$(badge "$PUR" "${G_FOLDER} #S")
BADGE_WEATHER=$(badge "$ORG" "#{weather}")
BADGE_ONLINE_YES=$(badge "$MNT" "${G_WIFI} ONLINE")
BADGE_ONLINE_NO=$(badge "$RED" "${G_NO_WIFI} OFFLINE")
BADGE_BATT=$(badge "$YEL" "#{battery_icon} #{battery_percentage}")

# Row 1 (info) badges — sit on bg0 too
BADGE_USER=$(badge "$CYA" "${G_USER} #(whoami)")
BADGE_HOST=$(badge "$PUR" "#h")
BADGE_PATH=$(badge "$MNT" "${G_FOLDER} #{b:pane_current_path}")
BADGE_CPU=$(badge "$RED" "${G_CPU} #($HOME/.tmux/plugins/tmux-cpu/scripts/cpu_percentage.sh)")
BADGE_CLOCK=$(badge "$CYA" "${G_CLOCK} %H:%M:%S")
BADGE_DATE=$(badge "$YEL" "%a %d %b")

# Window badges
WIN_INACTIVE_FMT="#[fg=${BG2},bg=${BG0}]${PL_RL}#[bg=${BG2},fg=${FG1}] #I ${G_TAG} #W #[fg=${BG2},bg=${BG0}]${PL_RR}"
WIN_CURRENT_FMT="#[fg=${MAG},bg=${BG0}]${PL_RL}#[bg=${MAG},fg=${BG0},bold] #I ${G_TAG} #W #[fg=${MAG},bg=${BG0}]${PL_RR}"

# ── Online status plugin: customize icons ──
ONLINE_ICON_YES="${G_WIFI} ONLINE"
ONLINE_ICON_NO="${G_NO_WIFI} OFFLINE"

cat > "$OUT" <<EOF
# ── city-blue — generated by build-city-blue.sh ──
# Re-run the script if Nerd Font glyphs ever disappear.

# ── Base ──
set -g status on
set -g status-position top
set -g status 2
set -g status-interval 5
set -g status-justify left

set -g status-style          "bg=${BG0},fg=${FG0}"
set -g status-left-style     "bg=${BG0},fg=${FG0}"
set -g status-right-style    "bg=${BG0},fg=${FG0}"
set -g status-left-length    250
set -g status-right-length   250

set -g message-style          "bg=${MAG},fg=${BG0},bold"
set -g message-command-style  "bg=${CYA},fg=${BG0},bold"
set -g mode-style             "bg=${PUR},fg=${BG0},bold"

set -g pane-border-style        "fg=${BG2}"
set -g pane-active-border-style "fg=${MAG}"
set -g display-panes-colour        "${BG2}"
set -g display-panes-active-colour "${MAG}"

setw -g clock-mode-colour "${CYA}"
setw -g clock-mode-style 24

# ── Window list (row 0) ──
setw -g window-status-separator " "
setw -g window-status-style          "bg=${BG0},fg=${FG1}"
setw -g window-status-current-style  "bg=${BG0},fg=${BG0},bold"
setw -g window-status-activity-style "bg=${YEL},fg=${BG0}"
setw -g window-status-bell-style     "bg=${RED},fg=${BG0},bold"

setw -g window-status-format         "${WIN_INACTIVE_FMT}"
setw -g window-status-current-format "${WIN_CURRENT_FMT}"

# ── Row 0: mode + session, then window list (default tmux composition), right widgets ──
set -g status-left "#{?client_prefix,${BADGE_PREFIX_C},#{?pane_in_mode,${BADGE_COPY_C},${BADGE_NORMAL_C}}} ${BADGE_SESSION} "

set -g status-right "${BADGE_WEATHER} ${BADGE_BATT} ${BADGE_ONLINE_YES}"

# ── Row 1: info row ──
# Plugin format placeholders (#{cpu_*}, #{battery_*}) only get post-processed
# in status-left/right by tpm plugins. For row 1 we call scripts directly.
set -g status-format[1] '#[bg=${BG0},fg=${FG1}]#[align=left] ${BADGE_USER} ${BADGE_HOST} ${BADGE_PATH}#[align=right]${BADGE_CPU} ${BADGE_CLOCK} ${BADGE_DATE} '

# ── Plugin icon overrides ──
# tmux-battery — city-blue tier glyphs
set -g @batt_icon_charge_tier8 "${G_BATT_8}"
set -g @batt_icon_charge_tier7 "${G_BATT_8}"
set -g @batt_icon_charge_tier6 "${G_BATT_6}"
set -g @batt_icon_charge_tier5 "${G_BATT_6}"
set -g @batt_icon_charge_tier4 "${G_BATT_4}"
set -g @batt_icon_charge_tier3 "${G_BATT_4}"
set -g @batt_icon_charge_tier2 "${G_BATT_2}"
set -g @batt_icon_charge_tier1 "${G_BATT_0}"
set -g @batt_icon_status_charging    "${G_BOLT}"
set -g @batt_icon_status_charged     "${G_CHECK}"
set -g @batt_icon_status_discharging ""

# tmux-online-status — show OFFLINE in red when down
set -g @online_icon  "${ONLINE_ICON_YES}"
set -g @offline_icon "${ONLINE_ICON_NO}"

# Pomodoro
set -g @pomodoro_on        "${G_TOMATO} "
set -g @pomodoro_complete  "${G_CHECK} "
set -g @pomodoro_pause     "${G_PAUSE} "
set -g @pomodoro_prompt_break    "${G_TOMATO} break? "
set -g @pomodoro_prompt_pomodoro "${G_CLOCK} start? "
EOF

echo "wrote $OUT"
